services:
  - type: web
    name: chat-backend
    env: node
    plan: starter
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm start"
    rootDir: backend

  - type: static
    name: chat-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    rootDir: frontend
